name: kyrgyz_kuhnya
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.2.0
  drift: ^2.28.1
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.13.1
  auto_route_generator: ^10.2.4
  drift_dev: ^2.28.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
